name: Master_Flow3

on:
  release:
    types: [published,prereleased]
    inputs:
      TestEnv:
        type: choice
        description: Please select environment
        options: 
        - AutomationOrg 
jobs:
  call-workflow-1:
    uses: ./.github/workflows/Flow1.yml
    with:
      TestEnv: ${{ github.event.inputs.TestEnv }}
    secrets: inherit
  call-workflow-2:
    if: ${{ always() }}  
    needs: call-workflow-1
    uses: ./.github/workflows/Flow2.yml
    with:
      TestEnv: ${{ github.event.inputs.TestEnv }}
    secrets: inherit
